Repository Icinga/ipl-scheduler, pull requests merged in 2023-08, with the labels that each got.

#46 Cron/OneOff: Always use default time zone
  src/Cron.php
  src/OneOff.php
  tests/CronTest.php
  tests/OneOffTest.php
Labels: bug, cla/signed

#47 composer.json: Install ipl dependencies from main branch in tests
  composer.json
Labels: cla/signed

#43 Github Actions: Add Phpstan
  .github/workflows/php.yml
  phpstan-baseline.neon
  phpstan.neon
  src/Common/Promises.php
  src/Common/Timers.php
  src/Cron.php
  src/OneOff.php
  src/RRule.php
  src/Scheduler.php
Labels: cla/signed, enhancement
